/*
	Constants used by the mod and its modules. Don't mess with them unless you know what you are doing.
*/
class XTFinishersConsts {
	// Listener priorities
	
	public const var DEFAULT_FINISHER_QUERY_DISPATCHER_PRIORITY, DEFAULT_DISMEMBER_QUERY_DISPATCHER_PRIORITY, DEFAULT_FINISHER_CAM_QUERY_DISPATCHER : int;
		default DEFAULT_FINISHER_QUERY_DISPATCHER_PRIORITY = 0;
		default DEFAULT_DISMEMBER_QUERY_DISPATCHER_PRIORITY = 10;
		default DEFAULT_FINISHER_CAM_QUERY_DISPATCHER = 0;
	
	public const var CUSTOM_SLOWDOWN_FINISHER_QUERY_DISPATCHER_PRIORITY, CUSTOM_SLOWDOWN_DISMEMBER_QUERY_DISPATCHER_PRIORITY : int;
		default CUSTOM_SLOWDOWN_FINISHER_QUERY_DISPATCHER_PRIORITY = 10;
		default CUSTOM_SLOWDOWN_DISMEMBER_QUERY_DISPATCHER_PRIORITY = 0;
	
	// Slowdown Module
	
	public const var SLOWDOWN_TYPE_FINISHER, SLOWDOWN_TYPE_DISMEMBER, SLOWDOWN_TYPE_CRIT : int;
		default SLOWDOWN_TYPE_FINISHER = 1;
		default SLOWDOWN_TYPE_DISMEMBER = 2;
		default SLOWDOWN_TYPE_CRIT = 3;
}